### ISSUE TITLE
Formatting

### ISSUE THREAD

**Issue by monkeytronics** [monkeytronics/monkeyr#12]
Urgent - Can't release hhi.rmd until it looks presentable. Plan is to release with Sections that are complete  by lunch time tomorrow.

* BUG in format of markdown. See all the cat("\n***"). Without these, the captions are pushed into the margin?!? Need to understand this.
* I need to add some more text here and there, but I'm seeing the same problem where it's getting shoved into the margin. 
* Kables are a mess - all different, and most of the formatting is not being applied somehow.
* Plots all need a once over. They are inconsistent. The report must look it's best. 

Once this is released, we can carefully continue to work on it with less pressure.

**Comment by mortonanalytics** [comment]
When you run the 'asis' chunks, the \n indicates a new line to ensure that markdown headers (#### in this case) are understood as headers. So, whenever you include markdown operators inside those 'asis' calls just make sure to add a line after.

For example,

`cat(paste0("\n", "#### Figure ", section_number, ".1.1 Estimated Correlation Segmented by ", target_var_Title,"\n"))`

**Comment by mortonanalytics** [comment]
I'm not sure what the kable formatting should look like and they all look the same to me. maybe a png of what they're supposed to look like would help.

**Comment by monkeytronics** [comment]
What might be better is if I let you suggest the best way. If you have a quick look at this output, you can see some of the problems: 
* The widths are random which looks messy
* They look "unfinished", if you see what I mean? 
* The collapse rows is a nice touch though. can we keep that?
* I was using formattable once upon a time and it looks very nice with some effort, but kableExtra looks like a much less painful option.
