### ISSUE TITLE
Cloud Install of package not working

### ISSUE THREAD

**Issue by monkeytronics** [monkeytronics/monkeyr#2]
figure out how to install monkeyr from github in cloud code. 

Currently running:
`Rscript -e "remotes::install_github('monkeytronics/monkeyr', ref='master')"`
on cloud linux machine. But the following code gets the error:

```
par_list <- monkeyr::make_params_list(
    filtered_obs           = obs,
    filtered_devices       = dev,
    filtered_weather       = weather,
    filtered_interventions = interv,
    fromTimeStamp          = from_ts,
    toTimeStamp            = to_ts
  )
```

> there is no package called ‘monkeyr’

**Comment by mortonanalytics** [comment]
Try doing the command using sudo rights. Installs are divided into two types: global and user. You probably need the install to be global and should be installed via sudo. I ran across this for shiny apps that ran using a different user name in Linux. Sudo install fixed it.

**Comment by monkeytronics** [comment]
Closing this as we figured it out. It was the sf package causing the package not to install.
