### ISSUE TITLE
Function Level Error Handling

### ISSUE THREAD

**Issue by monkeytronics** [monkeytronics/monkeyr#4]
At function level :
It would be nice to have a simple error handling mechanism. Light weight as possible. Even as basic as wrapping functions in a try catch with a well defined failure output (in C you'd normally pass arguments by address, fiddle about with stuff and return an integer error code (0 for no error), to let the calling code know that it had all worked. Is there a 'functional' equivalent in R we can use?

```
if (SUCCESS != myfunction(&arg1, &arg2)) {
 report error info and break
}
```

At Test Level :
It would be nice if this error could be thrown right up into the RMD file so that it is handled there. That way, modules of the RMD file could individually fail gracefully with a nice explanation. 

For example,  if you tried to add a map to a report, but none of the devices have any long, lat data, the map section might show a map with default long, lat set to Wellington, NZ with a big question mark in the middle of it and a comment below saying that we have no idea where the devices are.

**Comment by monkeytronics** [comment]
A bit of light reading suggests something like this might work:

```
  myfunc = function(vala, valb) {
    sum <- tryCatch(
      expr = {
        return (vala + valb)
      },
      error = function(e) {
        print(paste0("Caught Error = ", e)
        return("error")
      }
    )
    return (sum)
  }

  if (myfunc(1,"fdas") == "error"){
    abort and maybe send useful message to report (otherwise crack on)...
  }
```

**Comment by mortonanalytics** [comment]
If you prefer error catching, that's fine. In your if statement, you can use `stop("insert error message here")`

**Comment by monkeytronics** [comment]
Got some good error handling in place now.
